### ISSUE TITLE
Typo in https://www.nodejsdesignpatterns.com/blog/

### ISSUE THREAD

**Issue by oscaretu** [nodejs-design-patterns-book/nodejsdesignpatterns.com#18]
Hello.

There is a typo: excercise => exercise

![imagen](https://user-images.githubusercontent.com/2979926/194877537-e82b0522-49fd-4745-b1c2-9f51d3b42cfa.png)

**Comment by lmammino** [comment]
lol, i don't know why i am seeing this issue only now! thanks a lot for reporting it! <3
